from . import rehab_student
from . import rehab_discipline
from . import rehab_dormitory
from . import res_config_settings
from . import rehab_staff
from . import account_move
from . import account_account
from . import account_journal
from . import account_payment
from . import payment_method
