[options]
addons_path = c:\program files\odoo 19.0.20260308\server\odoo\addons,c:\Users\PC\.gemini\antigravity\scratch\som-rehab-odoo
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = openpg
db_password = openpgpwd
http_port = 8069
