{
    'name': 'Rehab Management',
    'version': '1.4',
    'summary': 'Odoo customization for Rehab and Dormitory Management',
    'description': """
        Customization for Rehab and Dormitory Management, 
        mirroring features from Somtherapy system.
    """,
    'author': 'Antigravity',
    'depends': ['base', 'mail', 'account', 'stock', 'purchase'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'data/initial_data.xml',
        'wizard/rehab_billing_wizard_views.xml',
        'wizard/rehab_staff_payment_wizard_views.xml',
        'wizard/rehab_financial_report_wizard_views.xml',
        'views/menus.xml',
        'views/res_config_settings_views.xml',
        'views/rehab_student_views.xml',
        'views/rehab_discipline_views.xml',
        'views/rehab_dormitory_views.xml',
        'views/rehab_staff_views.xml',
        'views/account_move_views.xml',
        'views/account_account_views.xml',
        'views/web_templates.xml',
        'report/financial_statement_templates.xml',
    ],
    'installable': True,
    'application': True,
}
