{
    'name': 'Rehab Management',
    'version': '1.25',
    'summary': 'Odoo customization for Rehab and Dormitory Management',
    'description': """
        Customization for Rehab and Dormitory Management, 
    
    """,
    'author': 'YOS ERP',
    'depends': ['base', 'mail', 'account', 'stock', 'purchase', 'payment'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'data/initial_data.xml',
        'data/sequences.xml',
        'wizard/rehab_billing_wizard_views.xml',
        'wizard/rehab_staff_payment_wizard_views.xml',
        'wizard/rehab_financial_report_wizard_views.xml',
        'wizard/rehab_daily_collection_wizard_views.xml',
        'views/menus.xml',
        'views/res_config_settings_views.xml',
        'views/rehab_student_views.xml',
        'views/rehab_discipline_views.xml',
        'views/rehab_dormitory_views.xml',
        'views/rehab_staff_views.xml',
        'views/account_move_views.xml',
        'views/account_account_views.xml',
        'views/account_journal_views.xml',
        'views/account_payment_views.xml',
        'views/payment_method_views.xml',
        'views/web_templates.xml',
        'report/financial_statement_templates.xml',
        'report/daily_collection_templates.xml',
        'report/student_statement_templates.xml',
    ],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'rehab_management/static/src/js/rehab_report_drilldown.js',
        ],
    },
}
